### PR TITLE
designate author in posts

### PR DESCRIPTION
**Pull request by dffischer**
When subscribed to multiple Viners in the same newsreader, this patch helps to tell them apart.

### CODE REVIEW

**Comment by tremby** [comment]
Looks perfect to me. Thanks! Just one thing, and I realize I'm an ass for this, but can you `git commit --amend` and capitalize the first letter of the commit message, and then `git push -f`? I like things consistent.

(Same for the other patches, please.)

**Comment by dffischer** [comment]
I am always open for stylistic corrections. All my commits are now capitalized.

**Comment by tremby** [comment]
There's a nice big article all about good commit messages here http://chris.beams.io/posts/git-commit/

Thanks for making the change.

**Comment by dffischer** [comment]
Another helpful piece for any reading list. I only knew [the classic by Tim Pope](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) and do not see it adhered to out in the wild very often,  especially with capitalized summaries. Nice to have people keeping up the good style.

Thanks for the merge.

**Pull request merged**
